<?php

namespace AppBundle\Entity;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllArray()
    {
        return $this->createQueryBuilder('g')
            ->getQuery()
            ->getArrayResult();
    }
}
